services:
  web-auth-service:
    build: 
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/web-auth-service:dev
    container_name: web-auth-service-dev
    ports:
      - 8081:8081
    networks:
      - adameds
    environment:
      # Application config
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      API_VERSION: ${API_VERSION}
    restart: always
networks:
  adameds:
    driver: bridge