version: '3.8'
services:
  web-auth-service:
    build: 
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/web-auth-service:dev
    container_name: web-auth-service-dev
    ports:
      - 8081:8081
    networks:
      - adameds
    environment:
      # Application config
      API_URL_VERSION: v3
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - type: bind
        source: /home/admin/adameds/private.key
        target: /web-auth/private.key
      - type: bind
        source: /home/admin/adameds/public.key
        target: /web-auth/public.key
      - type: bind
        source: /home/admin/adameds/.env.vault
        target: /web-auth/.env.vault
    restart: always
networks:
  adameds:
    driver: bridge